WebApplication1/WebApplication1/Controllers/LogInController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Data;
using WebApplication1.Models;
namespace WebApplication1.Controllers
{
    public class LogInController : Controller
    {
        private readonly ApplicationDbContext _db;
        public LogInController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }
        [HttpPost]
        public IActionResult login(User reg)//Login Varification
        {
            bool isValid = _db.User.Any(x => x.Email == reg.Email && x.Password == reg.Password);
            if (isValid) {
                return RedirectToAction("Index","Home");
            }
            else
            {
                ViewBag.Message = "Invalid Email or Password";
                return View(reg);
            }
        }

    }
}

WebApplication1/WebApplication1/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RegistrationController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registration(User reg)
        {
            if (ModelState.IsValid)
            {
                _db.User.Add(reg);
                _db.SaveChanges();
                return RedirectToAction("LogIn", "login");
            }
            return View(reg);
        }
    }
}

WebApplication1/WebApplication1/Views/LogIn/login.cshtml
@{
    ViewData["Title"] = "Login";
}

@model WebApplication1.Models.User

<form method="post" asp-action="Login" style="margin-top:10%">
    <div class="container p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row justify-content-center ">
            <h1 class="text-lg-center text-dark pl-3">Log In </h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6" style="padding:10px;">
                <div class="form-group row">
                    <div class="col-3 align-self-center">
                        <label asp-for="Email" class="font-weight-bold"> Email</label>
                    </div>
                    <div class="col w-75">
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 align-self-center">
                        <label asp-for="Password" class="font-weight-bold"> Password</label>
                    </div>
                    <div class="col w-75">
                        <input type="password" asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <div class="col-4">
                        <p class="">@ViewBag.Message </p>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <div class="offset-md-2 col-5">
                        <input type="submit" class="btn btn-dark btn-block border " name="Submit" value="Sign in" style="border-radius:25px" />
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <div class="offset-md-2 col-5">
                        <input asp-controller="Registration" asp-action="Registration" type="submit" class="btn btn-dark btn-block" name="Submit" value="Sign Up" style="border-radius:25px" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>